version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: frplus_db
    environment:
      POSTGRES_USER: frplus_user
      POSTGRES_PASSWORD: frplus_password
      POSTGRES_DB: frplus_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  evolution-api:
    image: atila/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - AUTHENTICATION_API_KEY=E493AE90-D9CA-4E38-95A7-526487122178
      - DATABASE_ENABLED=false
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  postgres_data:
  evolution_instances:
  evolution_store:
