services:
  postgres:
    image: postgres:15-alpine
    container_name: frplus_db
    environment:
      POSTGRES_USER: frplus_user
      POSTGRES_PASSWORD: frplus_password
      POSTGRES_DB: frplus_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: evolution_redis
    command: redis-server --appendonly yes
    volumes:
      - evolution_redis_data:/data
    restart: always

  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - AUTHENTICATION_API_KEY=E493AE90-D9CA-4E38-95A7-526487122178
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - "DATABASE_CONNECTION_URI=postgresql://frplus_user:frplus_password@postgres:5432/frplus_db?schema=evolution"
      - CACHE_REDIS_ENABLED=true
      - "CACHE_REDIS_URI=redis://redis:6379/0"
      - "CACHE_REDIS_PREFIX=evolution:"
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  postgres_data:
  evolution_instances:
  evolution_store:
  evolution_redis_data:
